### ISSUE TITLE
Blog on downloading, splitting and processing roads data

### ISSUE THREAD

**Issue by Robinlovelace** [geocompx/geocompx.org#10]
I propose a blog post in collaboration with Iwo @IwoA that will

- [ ] Show download road network data
- [ ] Split it at zone/cell boundaries or split links that are longer than a given distance (mention pros/cons speed of each option)
- [ ] Aggregate values on the network to raster grid cell e.g. with 500 m resolution

See here for some code: https://github.com/IwoA/st_split

**Comment by michaeldorman** [comment]
I didn't understand the third item, which aggregated values are going to be assigned to the raster cells?

**Comment by michaeldorman** [comment]
P.S. Great idea and very practical!

**Comment by Robinlovelace** [comment]
> I didn't understand the third item, which aggregated values are going to be assigned to the raster cells?

Will let Iwo answer but my thinking: length could be a good starting point. Length * traffic volumes (e.g. in AADT units) would be even better, even if the latter is synthetic data that we make up.

**Comment by IwoA** [comment]
Yes, sum of lengths of all roads in the raster cell is good for our small case study. It could be even more interesting if we summarise an osm road attribute like share of cycling roads.

**Comment by Robinlovelace** [comment]
Good stuff @IwoA feel free to port the .qmd doc into your repo and we can port it back in a new PR after `quarto preview` works. Nudge on #11 @Nowosad.
