### ISSUE TITLE
Publish blog post from OpenGeoHub

### ISSUE THREAD

**Issue by Robinlovelace** [geocompx/geocompx.org#2]
Porting this to here is the plan, only question from me: how to make the Quarto doc only run locally?

https://github.com/Robinlovelace/opengeohub2023/blob/main/blog.qmd

cc @Nowosad

**Comment by Nowosad** [comment]
I think (I may remember wrongly) that you only need to:
1. Put the blog post (after review) to the https://github.com/geocompx/geocompx.org/tree/main/post/2023 folder
2. Render the blog post locally
3. Push the changes to GitHub
4. Relax

**Comment by Robinlovelace** [comment]
Sounds good, especially the relax part
