### ISSUE TITLE
Slides for SDSL

### ISSUE THREAD

**Issue by Robinlovelace** [geocompx/geocompx.org#21]
As discussed with @Nowosad. 

Doable in the website I think, I plan to follow guidance here, any comments welcome: https://github.com/quarto-dev/quarto-cli/discussions/6939

**Comment by Robinlovelace** [comment]
| 11:00-12:30     | Learning resources and teaching methods                                                         | Robin / Jakub |

**Comment by Robinlovelace** [comment]
On day 2

**Comment by Nowosad** [comment]
https://jakubnowosad.com/sdsl2024/#/title-slide
